### ISSUE TITLE
Media gallery and images not avalaibles

### ISSUE THREAD

**Issue by theRAGEhero** [YunoHost-Apps/wordpress_ynh#162] opened 2022-05-08 16:47 UTC
Hello, 
I'm using ynh 4.3.6.3 (stable) and I installed Wordpress__7 (in the image) recently.

Unfortunately I cannot browse the media gallery. Other instances of Wordpress, that I've installed in the past, are working well.

![image](https://user-images.githubusercontent.com/39453005/167306314-04a4be61-a595-48d7-8658-daf06cfc9af9.png)

From sftp I noticed that there are different permissions.

![image](https://user-images.githubusercontent.com/39453005/167306492-ddf443b7-f91b-4386-9f4f-2410f41122a0.png)

I already tried to uninstall and install WP again but still the same problem.

Could you please help me?
Thank you

**Comment by tituspijean** [comment] 2022-05-09 14:21
Duplicate of https://github.com/YunoHost-Apps/wordpress_ynh/issues/156

**Closed as completed by tituspijean** 2022-05-09 14:21 UTC
